name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # your test steps here ...

  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for WIF

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/231383754275/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "gh-deployer@recommender-api-476122.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "recommender-api-476122"

      - name: Configure docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          IMAGE="us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api:${{ github.sha }}"
          docker build -t "$IMAGE" -f docker/service.Dockerfile .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          IMAGE="us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api:${{ github.sha }}"
          gcloud run deploy reco-api \
            --image "$IMAGE" \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
