name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest

    # Required for Workload Identity Federation
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # 1) Authenticate to GCP using WIF
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/231383754275/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "gh-deployer@recommender-api-476122.iam.gserviceaccount.com"
          # Make a JSON credentials file and point ADC at it
          create_credentials_file: true

      # 2) Install gcloud (it will automatically pick up the credentials file)
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "recommender-api-476122"

      # 3) Configure Docker to use Artifact Registry
      - name: Configure docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 4) Build and push the image
      - name: Build and push image
        env:
          IMAGE: "us-central1-docker.pkg.dev/${{ env.GCP_PROJECT }}/recommender-api-476122/reco/reco-api"
        run: |
          # Build using the service Dockerfile in ./docker
          gcloud builds submit --tag gcr.io/recommender-api-476122/us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api service.Dockerfile

      # 5) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api"
          gcloud run deploy reco-api \
            --image "$IMAGE" \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
