name: ci

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "No tests yet"

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: "read"
      id-token: "write"       # REQUIRED for WIF

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------------------------------------
      # 1️ Authenticate GitHub → Google Cloud (WIF)
      # -----------------------------------------------------------
      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "gha-deployer@PROJECT_ID.iam.gserviceaccount.com"
          create_credentials_file: true

      # -----------------------------------------------------------
      # 2️ Setup gcloud
      # -----------------------------------------------------------
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2

      # -----------------------------------------------------------
      # 3️ Configure Docker for Artifact Registry
      # -----------------------------------------------------------
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # -----------------------------------------------------------
      # 4️ Build image
      # -----------------------------------------------------------
      - name: Build container image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      # -----------------------------------------------------------
      # 5️ Push image
      # -----------------------------------------------------------
      - name: Push container image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # -----------------------------------------------------------
      # 6️ Deploy to Cloud Run
      # -----------------------------------------------------------
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated

    env:
      PROJECT_ID: recommender-api-476122
      REGION: us-central1
      SERVICE_NAME: reco-api
      ARTIFACT_REPO: reco
